#!/bin/bash
ROOTDIR="$(cd "$(dirname "$0")" && pwd -P)"

if [ -f "$ROOTDIR/networks/$1.sh" ]; then
	echo "Stopping \"$1\" session..."
	tmux kill-session -t "$1" >>/dev/null 2>&1
else
	echo "Invalid network: $1 (see $ROOTDIR/networks/ for valid networks)"
fi